# Install the apt prerequisites
language: node_js
node_js:
  - node
addons:
  apt:
    packages:
      - python-pygments
cache:
  directories:
    - "node_modules"

# Clean and don't fail
install:
  - rm -rf public || exit 0
  - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - sudo pip install awscli
  - npm install

# Build the website
script:
  - npm run index
  - hugo -b https://blog.xlab.tech -v
  - pwd

deploy:
  provider: script
  script: pwd && ls && npm run deploy
  on:
    branch: master

after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"