# Install the apt prerequisites
language: node_js
node_js:
  - node
addons:
  apt:
    packages:
      - python-pygments
cache:
  directories:
    - "node_modules"

# Clean and don't fail
install:
  - rm -rf public || exit 0
  - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install

# Build the website
script:
  - npm run index
  - hugo -b https://blog.xlab.tech -v

deploy:
  provider: s3
  access_key_id: "$AWS_ID"
  secret_access_key: "$AWS_TOKEN"
  bucket: "blog.xlab.tech"
  local_dir: public
  skip_cleanup: true
  region: eu-west-1