# Install the apt prerequisites
language: node_js
node_js:
  - node
addons:
  apt:
    packages:
      - python-pygments
cache:
  directories:
    - "node_modules"

# Clean and don't fail
install:
  - rm -rf public || exit 0
  - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p}}' | xargs wget
  - sudo dpkg -i hugo*.deb
  - npm install

# Build the website
script:
  - npm run index
  - hugo -b https://blog.xlab.tech -v

deploy:
  provider: s3
  access_key_id: $AWS_ID
  secret_access_key: $AWS_TOKEN
  bucket: "blog.xlab.tech"
  skip_cleanup: true
  region: "eu-west-1"