baseURL = "http://localhost:1313/"
languageCode = "es-ES"
theme = "xlab-tech"
footnoteReturnLinkContents = "↩"

[params]
  sidebarRecentLimit = 5
  subtitle = "A permanent blog"
  description = "Everything is awesome!"
  cover = "/images/jason-wong-352463-unsplash.jpg"
  coverCredit = "Photo by Jason Wong on Unsplash"
  [params.author]
    firstName = "xLab tech"
    lastName = "team"
    gender = "(fe)?male"
    userName = "xLab-tech-team"
    image = "/images/avatar.jpg"
    website = ""
    twitter = ""
    github = ""
    facebook = ""
    linkedin = ""
    gplus = ""

[permalinks]
  post = "/:year/:month/:title/"

  
